-- Unique lamp items
data:extend({
	{
		type = "item",
		name = "y-tinylamp",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/lamp-1-icon.png",
		group = "yuoki",
		subgroup = "y-lamps",
		place_result = "y-tinylamp",
		stack_size = 50,
		order = "la",
	},
	{
		type = "item",
		name = "y-powerlamp",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/lamps/hl2_icon.png",
		group = "yuoki",
		subgroup = "y-lamps",
		place_result = "y-powerlamp",
		stack_size = 50,
		order = "lb",
	},
	{
		type = "item",
		name = "y-lamp-alien",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/alien_lampe_icon.png",
		group = "yuoki",
		subgroup = "y-lamps",
		place_result = "y-lamp-alien",
		stack_size = 40,
		order = "lc",
	},
	{
		type = "item",
		name = "yi-monument1",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/monument-1-icon.png",
		group = "yuoki",
		subgroup = "y-lamps",
		place_result = "yi-monument1",
		stack_size = 5,
		order = "ld",
	},
})

-- Unique lamp recipes
data:extend({
	{
		type = "recipe",
		name = "y-tinylamp",
		enabled = true,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 1 },
			{ type = "item", name = "copper-cable", amount = 1 },
		},
		group = "yuoki",
		subgroup = "y-lamps",
		results = { { type = "item", name = "y-tinylamp", amount = 1 } },
		main_product = "y-tinylamp",
		order = "la",
	},
	{
		type = "recipe",
		name = "y-powerlamp",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/lamps/hl2_icon.png",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-raw-fuelnium", amount = 1 },
			{ type = "item", name = "steel-plate", amount = 1 },
			{ type = "item", name = "copper-plate", amount = 2 },
		},
		results = {
			{ type = "item", name = "y-powerlamp", amount = 1 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		main_product = "y-powerlamp",
		group = "yuoki",
		subgroup = "y-lamps",
		order = "lb",
	},
	{
		type = "recipe",
		name = "y-lamp-alien",
		enabled = true,
		ingredients = {
			{ type = "item", name = "steel-plate", amount = 3 },
			{ type = "item", name = "y-infused-uca2", amount = 1 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		group = "yuoki",
		subgroup = "y-lamps",
		results = { { type = "item", name = "y-lamp-alien", amount = 3 } },
		main_product = "y-lamp-alien",
		order = "lc",
	},
	{
		type = "recipe",
		name = "yi-monument1",
		enabled = true,
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/monument-1-icon.png",
		ingredients = {
			{ type = "item", name = "y-crystal-cnd", amount = 6 },
			{ type = "item", name = "y-unicomp-raw", amount = 12 },
			{ type = "item", name = "steel-plate", amount = 10 },
			{ type = "item", name = "y-orange-stuff", amount = 15 },
		},
		group = "yuoki",
		subgroup = "y-lamps",
		results = {
			{ type = "item", name = "yi-monument1", amount = 1 },
			{ type = "item", name = "y_rwtechsign", amount = 10 },
		},
		main_product = "yi-monument1",
		order = "ld",
	},
})

-- Unique lamp entities using yi.lib.entity.make_lamp()
data:extend({
	yi.lib.entity.make_lamp("y-tinylamp", {
		icon = "__Yuoki__/graphics/icons/lamp-1-icon.png",
		energy_usage_per_tick = "4kW",
		light = { intensity = 0.8, size = 60, color = { r = 1.0, g = 0.95, b = 0.8 } },
		picture_off = {
			filename = "__Yuoki__/graphics/entity/power_lamp_v2.png",
			priority = "high",
			width = 32,
			height = 48,
			shift = { 0, -0.3 },
		},
		picture_on = {
			filename = "__Yuoki__/graphics/entity/power_lamp_v2.png",
			priority = "high",
			width = 32,
			height = 48,
			x = 32,
			shift = { 0, -0.3 },
		},
		circuit_wire_max_distance = 14.5,
	}),
	yi.lib.entity.make_lamp("y-powerlamp", {
		icon = "__Yuoki__/graphics/entity/lamps/hl2_icon.png",
		energy_usage_per_tick = "10kW",
		light = { intensity = 0.9, size = 80, color = { r = 0.95, g = 1.0, b = 0.8 } },
		picture_off = {
			filename = "__Yuoki__/graphics/entity/lamps/lampe_gelb_off.png",
			priority = "high",
			width = 96,
			height = 128,
			scale = 0.5,
			shift = { 0, -0.5 },
		},
		picture_on = {
			filename = "__Yuoki__/graphics/entity/lamps/lampe_gelb_on.png",
			priority = "high",
			width = 96,
			height = 128,
			scale = 0.5,
			shift = { 0, -0.5 },
		},
		circuit_wire_max_distance = 14.5,
	}),
	yi.lib.entity.make_lamp("y-lamp-alien", {
		icon = "__Yuoki__/graphics/icons/alien_lampe_icon.png",
		energy_usage_per_tick = "20kW",
		light = { intensity = 0.9, size = 180, color = { r = 1.0, g = 0.9, b = 1.0 } },
		picture_off = {
			filename = "__Yuoki__/graphics/entity/lamps/al2_off.png",
			priority = "high",
			width = 64,
			height = 128,
			shift = { 0, -0.5 },
		},
		picture_on = {
			filename = "__Yuoki__/graphics/entity/lamps/al2_on.png",
			priority = "high",
			width = 64,
			height = 128,
			shift = { 0, -0.5 },
		},
		circuit_wire_max_distance = 14.5,
	}),
	yi.lib.entity.make_lamp("yi-monument1", {
		icon = "__Yuoki__/graphics/entity/monument-1-icon.png",
		health = 500,
		minable = { hardness = 0.5, mining_time = 1.0, result = "yi-monument1" },
		corpse = "big-remnants",
		collision_box = { { -2.2, -2.2 }, { 2.2, 2.2 } },
		selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
		energy_source = {
			type = "electric",
			input_priority = "secondary",
			usage_priority = "secondary-input",
		},
		energy_usage_per_tick = "250kW",
		light = { intensity = 1.0, size = 140 },
		picture_off = {
			filename = "__Yuoki__/graphics/entity/monument-1.png",
			priority = "high",
			width = 256,
			height = 256,
			shift = { 2.0, -1.5 },
		},
		picture_on = {
			filename = "__Yuoki__/graphics/entity/monument-1.png",
			priority = "high",
			width = 256,
			height = 256,
			x = 256,
			shift = { 2.0, -1.5 },
		},
		circuit_wire_max_distance = 22.5,
	}),
})

-- Color lamp prototypes using library function
local color_lamps = yi.lib.lamp.make_color_set({"red", "green", "blue", "yellow"}, {
	health = 75,
	energy_usage_per_tick = "5kW",
	light = { intensity = 0.25, size = 8 },
	circuit_wire_max_distance = 22.5,
	picture_shift = { 0.3125, -0.125 },
	order_prefix = "2",
	ingredients = {
		{ type = "item", name = "y_structure_element", amount = 1 },
		{ type = "item", name = "y-chip-1", amount = 1 },
	},
})
data:extend({
	color_lamps.red.item, color_lamps.red.recipe, color_lamps.red.entity,
	color_lamps.green.item, color_lamps.green.recipe, color_lamps.green.entity,
	color_lamps.blue.item, color_lamps.blue.recipe, color_lamps.blue.entity,
	color_lamps.yellow.item, color_lamps.yellow.recipe, color_lamps.yellow.entity,
})
