data:extend({
	-- smart yuoki-inserter L2
	{
		type = "recipe",
		name = "y_inserter_diagonal",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
			{ type = "item", name = "y-conductive-wire-1", amount = 4 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		results = {
			{ type = "item", name = "y_inserter_diagonal", amount = 1 },
		},
		main_product = "y_inserter_diagonal",
		subgroup = "j-y-logi-2",
		order = "e",
	},
	{
		type = "item",
		name = "y_inserter_diagonal",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/ins_diagonal.png",
		group = "yuoki",
		subgroup = "j-y-logi-2",
		order = "e",
		place_result = "y_inserter_diagonal",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y_inserter_diagonal", {
		icon = "__Yuoki__/graphics/entity/inserters/ins_diagonal.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.9kW",
		pickup_position = { -1.2, -1 },
		insert_position = { 1.2, 1.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_base_3.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_3.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_3.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/special_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

	-- smart yuoki-inserter evade inserter
	{
		type = "recipe",
		name = "y_inserter_evade_shortR",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
			{ type = "item", name = "copper-cable", amount = 4 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		results = {
			{ type = "item", name = "y_inserter_evade_shortR", amount = 1 },
		},
		main_product = "y_inserter_evade_shortR",
		subgroup = "j-y-logi-2",
		order = "f",
	},
	{
		type = "item",
		name = "y_inserter_evade_shortR",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/ins_evade_right_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-2",
		order = "f",
		place_result = "y_inserter_evade_shortR",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y_inserter_evade_shortR", {
		icon = "__Yuoki__/graphics/entity/inserters/ins_evade_right_icon.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.9kW",
		pickup_position = { 1.2, -1 },
		insert_position = { 1.2, 1.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_base_3.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_3.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_3.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/special_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

	-- smart yuoki-inserter evade inserter
	{
		type = "recipe",
		name = "y_inserter_evade_shortL",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
			{ type = "item", name = "copper-cable", amount = 4 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		results = {
			{ type = "item", name = "y_inserter_evade_shortL", amount = 1 },
		},
		main_product = "y_inserter_evade_shortL",
		subgroup = "j-y-logi-2",
		order = "g",
	},
	{
		type = "item",
		name = "y_inserter_evade_shortL",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/ins_evade_left_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-2",
		order = "g",
		place_result = "y_inserter_evade_shortL",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y_inserter_evade_shortL", {
		icon = "__Yuoki__/graphics/entity/inserters/ins_evade_left_icon.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.9kW",
		pickup_position = { -1.2, -1 },
		insert_position = { -1.2, 1.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_base_3.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_3.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_3.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/special_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

})
