data:extend({

	-- fast yuoki-inserter
	{
		type = "recipe",
		name = "y-inserter-fast",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/y_smart_ins_icon.png",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y_structure_element", amount = 3 },
			{ type = "item", name = "y-raw-fuelnium", amount = 1 },
			{ type = "item", name = "y-chip-1", amount = 1 },
		},
		results = {
			{ type = "item", name = "y-inserter-fast", amount = 1 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		main_product = "y-inserter-fast",
		subgroup = "j-y-logi-1",
		order = "a",
	},
	{
		type = "item",
		name = "y-inserter-fast",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/y_smart_ins_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-1",
		order = "a",
		place_result = "y-inserter-fast",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y-inserter-fast", {
		icon = "__Yuoki__/graphics/entity/inserters/y_smart_ins_icon.png",
		bulk = true,
		energy_per_movement = "6kJ",
		energy_per_rotation = "6kJ",
		extension_speed = 0.1,
		rotation_speed = 0.1,
		drain = "0.75kW",
		insert_position = { 0, 1.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_whi_hb.png",
			priority = "extra-high",
			width = 8,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_white_ihc.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_white_ihc.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/w_insbase.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("long"),
	}),

	-- long yuoki-inserter
	{
		type = "recipe",
		name = "y-inserter-s4",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/ins_red_icon.png",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y_structure_element", amount = 3 },
			{ type = "item", name = "y-inserter-fast", amount = 1 },
		},
		results = {
			{ type = "item", name = "y-inserter-s4", amount = 1 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		main_product = "y-inserter-s4",
		order = "c",
		subgroup = "j-y-logi-1",
	},
	{
		type = "item",
		name = "y-inserter-s4",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/ins_red_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-1",
		order = "c",
		place_result = "y-inserter-s4",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y-inserter-s4", {
		icon = "__Yuoki__/graphics/entity/inserters/ins_red_icon.png",
		bulk = true,
		energy_per_movement = "6kJ",
		energy_per_rotation = "6kJ",
		extension_speed = 0.12,
		rotation_speed = 0.02,
		drain = "0.7kW",
		insert_position = { 0, 4.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_long_ins_base.png",
			priority = "extra-high",
			width = 8,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_long_ins_closed.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_long_ins_closed.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0 },
				filename = "__Yuoki__/graphics/entity/inserters/lng_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("long"),
	}),

	-- smart yuoki-inserter
	{
		type = "recipe",
		name = "y-inserter-smart",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-fast", amount = 1, },
			{ type = "item", name = "y-chip-2", amount = 2, },
			{ type = "item", name = "y-infused-uca2", amount = 1, }
		},
		results = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
		},
		main_product = "y-inserter-smart",
		subgroup = "j-y-logi-1",
		order = "b",
	},
	{
		type = "item",
		name = "y-inserter-smart",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/ins_cyan_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-1",
		order = "b",
		place_result = "y-inserter-smart",
		stack_size = 50,
	},

	yi.lib.entity.make_inserter("y-inserter-smart", {
		icon = "__Yuoki__/graphics/entity/inserters/ins_cyan_icon.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.10,
		drain = "0.8kW",
		pickup_position = { 0, -1 },
		insert_position = { 0, 1.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_fast_inserter_hand_base.png",
			priority = "extra-high",
			width = 8,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_fast_inserter_hand_closed.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/yi_fast_inserter_hand_closed.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/yi_fast_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			filter_count = 5,
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

	-- smart long yuoki-inserter
	{
		type = "recipe",
		name = "y-inserter-smart-long",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y_structure_element", amount = 3 },
			{ type = "item", name = "y-inserter-smart", amount = 1 },
		},
		results = {
			{ type = "item", name = "y-inserter-smart-long", amount = 1 },
		},
		main_product = "y-inserter-smart-long",
		subgroup = "j-y-logi-1",
		order = "c",
	},

	{
		type = "item",
		name = "y-inserter-smart-long",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/inserter_long_smart.png",
		group = "yuoki",
		subgroup = "j-y-logi-1",
		order = "c",
		place_result = "y-inserter-smart-long",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y-inserter-smart-long", {
		icon = "__Yuoki__/graphics/entity/inserters/inserter_long_smart.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.8kW",
		pickup_position = { 0, -2 },
		insert_position = { 0, 2.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/longsmart-base-s.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/longsmart-hand-s.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/longsmart-hand-s.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/limegreen_base.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

	-- smart yuoki-inserter R2
	{
		type = "recipe",
		name = "y_inserter_smart_rightR2",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
			{ type = "item", name = "y-conductive-wire-1", amount = 2 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		results = {
			{ type = "item", name = "y_inserter_smart_rightR2", amount = 1 },
		},
		main_product = "y_inserter_smart_rightR2",
		subgroup = "j-y-logi-2",
		order = "b",
	},
	{
		type = "item",
		name = "y_inserter_smart_rightR2",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_rights_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-2",
		order = "b",
		place_result = "y_inserter_smart_rightR2",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y_inserter_smart_rightR2", {
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_rights_icon.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.8kW",
		pickup_position = { 0, -1 },
		insert_position = { -1.2, 1.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special-base.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/special_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			filter_count = 5,
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

	-- smart yuoki-inserter L2
	{
		type = "recipe",
		name = "y_inserter_smart_leftR2",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
			{ type = "item", name = "y-conductive-wire-1", amount = 2 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		results = {
			{ type = "item", name = "y_inserter_smart_leftR2", amount = 1 },
		},
		main_product = "y_inserter_smart_leftR2",
		subgroup = "j-y-logi-2",
		order = "a",
	},
	{
		type = "item",
		name = "y_inserter_smart_leftR2",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_lefts_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-2",
		order = "a",
		place_result = "y_inserter_smart_leftR2",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y_inserter_smart_leftR2", {
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_lefts_icon.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.8kW",
		pickup_position = { 0, -1 },
		insert_position = { 1.2, 1.2 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special-base.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/special_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			filter_count = 5,
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

	-- smart yuoki-inserter RR
	{
		type = "recipe",
		name = "y_inserter_smart_RR",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
			{ type = "item", name = "y-conductive-wire-1", amount = 2 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		results = {
			{ type = "item", name = "y_inserter_smart_RR", amount = 1 },
		},
		main_product = "y_inserter_smart_RR",
		subgroup = "j-y-logi-2",
		order = "c",
	},
	{
		type = "item",
		name = "y_inserter_smart_RR",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_right_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-2",
		order = "c",
		place_result = "y_inserter_smart_RR",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y_inserter_smart_RR", {
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_right_icon.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.8kW",
		pickup_position = { 0, -1 },
		insert_position = { -1.2, 0 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special-base.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_2.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_2.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/special_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			filter_count = 5,
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),

	-- smart yuoki-inserter LL
	{
		type = "recipe",
		name = "y_inserter_smart_LL",
		enabled = true,
		ingredients = {
			{ type = "item", name = "y-inserter-smart", amount = 1 },
			{ type = "item", name = "y-conductive-wire-1", amount = 2 },
			{ type = "item", name = "y_rwtechsign", amount = 1 },
		},
		results = {
			{ type = "item", name = "y_inserter_smart_LL", amount = 1 },
		},
		main_product = "y_inserter_smart_LL",
		subgroup = "j-y-logi-2",
		order = "d",
	},
	{
		type = "item",
		name = "y_inserter_smart_LL",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_left_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-2",
		order = "d",
		place_result = "y_inserter_smart_LL",
		stack_size = 50,
	},
	yi.lib.entity.make_inserter("y_inserter_smart_LL", {
		icon = "__Yuoki__/graphics/entity/inserters/special_ins_left_icon.png",
		bulk = true,
		energy_per_movement = "6.5kJ",
		energy_per_rotation = "6.5kJ",
		extension_speed = 0.1,
		rotation_speed = 0.08,
		drain = "0.8kW",
		pickup_position = { 0, -1 },
		insert_position = { 1.2, 0 },
		hand_base_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special-base.png",
			priority = "extra-high",
			width = 12,
			height = 34,
		},
		hand_closed_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_2.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		hand_open_picture = {
			filename = "__Yuoki__/graphics/entity/inserters/special_ihc_2.png",
			priority = "extra-high",
			width = 18,
			height = 41,
			shift = { -0.0625, 0 },
		},
		shadow_pictures = yi.lib.entity.make_inserter_shadow_pictures(),
		platform_picture = {
			sheet = {
				priority = "extra-high",
				width = 48,
				height = 48,
				shift = { 0.225, 0.1 },
				filename = "__Yuoki__/graphics/entity/inserters/special_ins_sheet.png",
			},
		},
		working_sound = yi.lib.entity.make_inserter_working_sound("fast"),
		overrides = {
			filter_count = 5,
			programmable = true,
			uses_arm_movement = "basic-inserter",
			vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		},
	}),
})
