-- Get shared wall diode properties from yi library
local yi_wall_diodes = yi.lib.entity.make_wall_diodes()

-- Shared circuit properties for walls
local wall_circuit_wire_connection_point = circuit_connector_definitions["wall"].points
local wall_circuit_wire_max_distance = default_circuit_wire_max_distance
local wall_default_output_signal = data.is_demo and { type = "virtual", name = "signal-green" } or { type = "virtual", name = "signal-G" }

-- Helper function for standard wall connected_wall_visualization
local function make_wall_connected_visualization()
	return {
		filename = "__core__/graphics/arrows/underground-lines.png",
		priority = "high",
		width = 64,
		height = 64,
		scale = 0.5,
	}
end

-- Helper function for standard wall picture sprite
local function wall_sprite(path, w, h, shift)
	return {
		filename = path,
		priority = "extra-high",
		width = w or 64,
		height = h or 64,
		shift = shift or { 0.40625, 0 },
	}
end

data:extend({
	{
		type = "wall",
		name = "y_wood_wall",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/walls/wood_wall_icon.png",
		flags = { "placeable-neutral", "player-creation" },
		collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
		selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
		minable = { mining_time = 0.2, result = "y_wood_wall" },
		max_health = 250,
		corpse = "wall-remnants",
		repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
		mined_sound = sound_variations("__base__/sound/car-wood-impact", 5, 0.7),
		repair_speed_modifier = 2,
		fast_replaceable_group = "wall",
		vehicle_impact_sound = sound_variations("__base__/sound/car-stone-impact", 5, 0.7),
		connected_wall_visualization = make_wall_connected_visualization(),
		wall_diode_green = yi_wall_diodes.wall_diode_green,
		wall_diode_green_light_top = yi_wall_diodes.wall_diode_green_light_top,
		wall_diode_green_light_right = yi_wall_diodes.wall_diode_green_light_right,
		wall_diode_green_light_bottom = yi_wall_diodes.wall_diode_green_light_bottom,
		wall_diode_green_light_left = yi_wall_diodes.wall_diode_green_light_left,
		wall_diode_red = yi_wall_diodes.wall_diode_red,
		wall_diode_red_light_top = yi_wall_diodes.wall_diode_red_light_top,
		wall_diode_red_light_right = yi_wall_diodes.wall_diode_red_light_right,
		wall_diode_red_light_bottom = yi_wall_diodes.wall_diode_red_light_bottom,
		wall_diode_red_light_left = yi_wall_diodes.wall_diode_red_light_left,
		circuit_wire_connection_point = wall_circuit_wire_connection_point,
		circuit_wire_max_distance = wall_circuit_wire_max_distance,
		default_output_signal = wall_default_output_signal,
		resistances = {
			{ type = "physical", decrease = 2, percent = 20 },
			{ type = "impact", decrease = 30, percent = 30 },
			{ type = "explosion", decrease = 10, percent = 30 },
			{ type = "fire", percent = 10 },
			{ type = "laser", percent = 50 },
			{ type = "acid", percent = 30 },
		},
		pictures = {
			single = { wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall.png") },
			straight_vertical = {
				wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_u.png"),
				wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_u1.png"),
			},
			straight_horizontal = {
				wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_we.png"),
				wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_we1.png"),
				wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_we2.png"),
			},
			corner_right_down = { wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_cru.png") },
			corner_left_down = { wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_clu.png") },
			t_up = { wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_tu.png") },
			ending_right = { wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_el.png") },
			ending_left = { wall_sprite("__Yuoki__/graphics/entity/walls/wood_wall_er.png") },
		},
	},
	{
		type = "wall",
		name = "y-mud-wall",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/m_wall_icon.png",
		flags = { "placeable-neutral", "player-creation" },
		collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
		selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
		minable = { mining_time = 0.2, result = "y-mud-wall" },
		max_health = 420,
		corpse = "wall-remnants",
		repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
		mined_sound = { filename = "__base__/sound/deconstruct-bricks.ogg" },
		repair_speed_modifier = 2,
		fast_replaceable_group = "wall",
		vehicle_impact_sound = { filename = "__base__/sound/car-stone-impact.ogg", volume = 1.0 },
		connected_wall_visualization = make_wall_connected_visualization(),
		wall_diode_green = yi_wall_diodes.wall_diode_green,
		wall_diode_green_light_top = yi_wall_diodes.wall_diode_green_light_top,
		wall_diode_green_light_right = yi_wall_diodes.wall_diode_green_light_right,
		wall_diode_green_light_bottom = yi_wall_diodes.wall_diode_green_light_bottom,
		wall_diode_green_light_left = yi_wall_diodes.wall_diode_green_light_left,
		wall_diode_red = yi_wall_diodes.wall_diode_red,
		wall_diode_red_light_top = yi_wall_diodes.wall_diode_red_light_top,
		wall_diode_red_light_right = yi_wall_diodes.wall_diode_red_light_right,
		wall_diode_red_light_bottom = yi_wall_diodes.wall_diode_red_light_bottom,
		wall_diode_red_light_left = yi_wall_diodes.wall_diode_red_light_left,
		circuit_wire_connection_point = wall_circuit_wire_connection_point,
		circuit_wire_max_distance = wall_circuit_wire_max_distance,
		default_output_signal = wall_default_output_signal,
		resistances = {
			{ type = "physical", decrease = 3, percent = 40 },
			{ type = "explosion", decrease = 10, percent = 30 },
			{ type = "impact", decrease = 50, percent = 60 },
			{ type = "fire", percent = 100 },
			{ type = "laser", percent = 50 },
			{ type = "acid", percent = 30 },
		},
		pictures = {
			single = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/m_wall_r19.png") },
			straight_vertical = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/m_wall_r19_u.png") },
			straight_horizontal = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/m_wall_r19_we.png") },
			corner_right_down = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/m_wall_r19_cru.png") },
			corner_left_down = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/m_wall_r19_clu.png") },
			t_up = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/m_wall_r19_tu.png") },
			ending_right = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/mud_wall_el.png") },
			ending_left = { wall_sprite("__Yuoki__/graphics/entity/mud_wall/mud_wall_er.png") },
		},
	},
	{
		type = "wall",
		name = "y-rare-wall-basic",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/rareore-wall-icon.png",
		flags = { "placeable-neutral", "player-creation" },
		collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
		selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
		minable = { mining_time = 0.2, result = "y-rare-wall-basic" },
		max_health = 770,
		corpse = "wall-remnants",
		repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
		mined_sound = { filename = "__base__/sound/deconstruct-bricks.ogg" },
		repair_speed_modifier = 2,
		fast_replaceable_group = "wall",
		vehicle_impact_sound = { filename = "__base__/sound/car-stone-impact.ogg", volume = 1.0 },
		connected_wall_visualization = make_wall_connected_visualization(),
		wall_diode_green = yi_wall_diodes.wall_diode_green,
		wall_diode_green_light_top = yi_wall_diodes.wall_diode_green_light_top,
		wall_diode_green_light_right = yi_wall_diodes.wall_diode_green_light_right,
		wall_diode_green_light_bottom = yi_wall_diodes.wall_diode_green_light_bottom,
		wall_diode_green_light_left = yi_wall_diodes.wall_diode_green_light_left,
		wall_diode_red = yi_wall_diodes.wall_diode_red,
		wall_diode_red_light_top = yi_wall_diodes.wall_diode_red_light_top,
		wall_diode_red_light_right = yi_wall_diodes.wall_diode_red_light_right,
		wall_diode_red_light_bottom = yi_wall_diodes.wall_diode_red_light_bottom,
		wall_diode_red_light_left = yi_wall_diodes.wall_diode_red_light_left,
		circuit_wire_connection_point = wall_circuit_wire_connection_point,
		circuit_wire_max_distance = wall_circuit_wire_max_distance,
		default_output_signal = wall_default_output_signal,
		resistances = {
			{ type = "physical", decrease = 4, percent = 50 },
			{ type = "explosion", decrease = 5, percent = 50 },
			{ type = "impact", decrease = 50, percent = 60 },
			{ type = "fire", percent = 100 },
			{ type = "laser", percent = 50 },
			{ type = "acid", percent = 40 },
		},
		pictures = {
			single = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/rare1-wall.png", 36, 44, { 0, 0 }) },
			straight_vertical = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/bw-ns.png", 36, 44, { 0, -0.15 }) },
			straight_horizontal = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/bw-we.png", 36, 44, { 0, 0 }) },
			corner_right_down = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/bw_cr.png", 36, 44, { 0, 0 }) },
			corner_left_down = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/bw_cl.png", 36, 44, { 0, 0 }) },
			t_up = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/bw_tu.png", 36, 44, { 0, 0 }) },
			ending_right = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/bw-end-left.png", 36, 44, { 0, 0 }) },
			ending_left = { wall_sprite("__Yuoki__/graphics/entity/blue_wall/bw-end-right.png", 36, 44, { 0, 0 }) },
		},
	},
	{
		type = "wall",
		name = "y-rare-wall-adv",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/rare2-wall-icon2.png",
		flags = { "placeable-neutral", "player-creation" },
		collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
		selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
		minable = { mining_time = 0.2, result = "y-rare-wall-adv" },
		max_health = 1000,
		corpse = "wall-remnants",
		repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
		mined_sound = { filename = "__base__/sound/deconstruct-bricks.ogg" },
		repair_speed_modifier = 2,
		fast_replaceable_group = "wall",
		vehicle_impact_sound = { filename = "__base__/sound/car-stone-impact.ogg", volume = 1.0 },
		connected_wall_visualization = make_wall_connected_visualization(),
		wall_diode_green = yi_wall_diodes.wall_diode_green,
		wall_diode_green_light_top = yi_wall_diodes.wall_diode_green_light_top,
		wall_diode_green_light_right = yi_wall_diodes.wall_diode_green_light_right,
		wall_diode_green_light_bottom = yi_wall_diodes.wall_diode_green_light_bottom,
		wall_diode_green_light_left = yi_wall_diodes.wall_diode_green_light_left,
		wall_diode_red = yi_wall_diodes.wall_diode_red,
		wall_diode_red_light_top = yi_wall_diodes.wall_diode_red_light_top,
		wall_diode_red_light_right = yi_wall_diodes.wall_diode_red_light_right,
		wall_diode_red_light_bottom = yi_wall_diodes.wall_diode_red_light_bottom,
		wall_diode_red_light_left = yi_wall_diodes.wall_diode_red_light_left,
		circuit_wire_connection_point = wall_circuit_wire_connection_point,
		circuit_wire_max_distance = wall_circuit_wire_max_distance,
		default_output_signal = wall_default_output_signal,
		resistances = {
			{ type = "physical", decrease = 6, percent = 60 },
			{ type = "explosion", decrease = 5, percent = 50 },
			{ type = "impact", decrease = 80, percent = 70 },
			{ type = "fire", percent = 100 },
			{ type = "laser", percent = 70 },
			{ type = "acid", percent = 50 },
		},
		pictures = {
			single = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_single.png", 36, 44, { 0, 0 }) },
			straight_vertical = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_ns.png", 36, 44, { 0, 0 }) },
			straight_horizontal = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_we.png", 36, 44, { 0, 0 }) },
			corner_right_down = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_cr.png", 36, 44, { 0, 0 }) },
			corner_left_down = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_cl.png", 36, 44, { 0, 0 }) },
			t_up = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_tu.png", 36, 44, { 0, 0 }) },
			ending_right = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_el.png", 36, 44, { 0, 0 }) },
			ending_left = { wall_sprite("__Yuoki__/graphics/entity/red_wall/rw_er.png", 36, 44, { 0, 0 }) },
		},
	},
	{
		type = "wall",
		name = "y-wall-forcefield",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/wall-forcefield-icon.png",
		flags = { "placeable-neutral", "player-creation" },
		collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
		selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
		minable = { mining_time = 0.2, result = "y-wall-forcefield" },
		max_health = 800,
		corpse = "wall-remnants",
		repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
		mined_sound = { filename = "__base__/sound/deconstruct-bricks.ogg" },
		repair_speed_modifier = 2,
		fast_replaceable_group = "wall",
		vehicle_impact_sound = { filename = "__base__/sound/car-stone-impact.ogg", volume = 1.0 },
		connected_wall_visualization = make_wall_connected_visualization(),
		wall_diode_green = yi_wall_diodes.wall_diode_green,
		wall_diode_green_light_top = yi_wall_diodes.wall_diode_green_light_top,
		wall_diode_green_light_right = yi_wall_diodes.wall_diode_green_light_right,
		wall_diode_green_light_bottom = yi_wall_diodes.wall_diode_green_light_bottom,
		wall_diode_green_light_left = yi_wall_diodes.wall_diode_green_light_left,
		wall_diode_red = yi_wall_diodes.wall_diode_red,
		wall_diode_red_light_top = yi_wall_diodes.wall_diode_red_light_top,
		wall_diode_red_light_right = yi_wall_diodes.wall_diode_red_light_right,
		wall_diode_red_light_bottom = yi_wall_diodes.wall_diode_red_light_bottom,
		wall_diode_red_light_left = yi_wall_diodes.wall_diode_red_light_left,
		circuit_wire_connection_point = wall_circuit_wire_connection_point,
		circuit_wire_max_distance = wall_circuit_wire_max_distance,
		default_output_signal = wall_default_output_signal,
		attack_reaction = {
			{
				---- how far the mirroring works
				range = 3,
				---- what kind of damage triggers the mirroring
				---- if not present then anything triggers the mirroring
				damage_type = "physical",
				---- caused damage will be multiplied by this and added to the subsequent damages
				reaction_modifier = 0.25,
				action = {
					type = "direct",
					action_delivery = {
						{
							type = "instant",
							target_effects = {
								{
									type = "create-sticker",
									sticker = "stun-sticker",
								},
								{
									type = "push-back",
									distance = 1,
								},
							},
						},
						{
							type = "beam",
							beam = "electric-beam-no-sound",
							max_length = 1,
							duration = 1,
							source_offset = { 0, -1.31439 },
						},
					},
				},
			},
		},
		resistances = {
			{ type = "physical", decrease = 5, percent = 90 },
			{ type = "explosion", decrease = 2, percent = 50 },
			{ type = "fire", percent = 100 },
			{ type = "acid", percent = 80 },
		},
		pictures = {
			single = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_single.png", 48, 48, { 0.2, 0 }) },
			straight_vertical = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_ns.png", 48, 48, { 0.2, 0 }) },
			straight_horizontal = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_we.png", 48, 48, { 0.2, 0 }) },
			corner_right_down = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_cr.png", 48, 48, { 0.2, 0 }) },
			corner_left_down = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_cl.png", 48, 48, { 0.2, 0 }) },
			t_up = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_single.png", 48, 48, { 0.2, 0 }) },
			ending_right = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_el.png", 48, 48, { 0.2, 0 }) },
			ending_left = { wall_sprite("__Yuoki__/graphics/entity/wall_force/wf_er.png", 48, 48, { 0.2, 0 }) },
		},
	},
	{
		type = "wall",
		name = "y_wall22_hardic",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/walls/wall_hardic_icon.png",
		flags = { "placeable-neutral", "player-creation" },
		collision_box = { { -0.9, -0.9 }, { 0.8, 0.8 } },
		selection_box = { { -1.0, -1.0 }, { 1.0, 1.0 } },
		drawing_box = { { -1, -1.5 }, { 1, 1.5 } },
		minable = { mining_time = 0.2, result = "y_wall22_hardic" },
		max_health = 4000,
		corpse = "wall-remnants",
		repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
		mined_sound = { filename = "__base__/sound/deconstruct-bricks.ogg" },
		repair_speed_modifier = 2,
		fast_replaceable_group = "wall",
		vehicle_impact_sound = { filename = "__base__/sound/car-stone-impact.ogg", volume = 1.0 },
		connected_wall_visualization = make_wall_connected_visualization(),
		wall_diode_green = yi_wall_diodes.wall_diode_green,
		wall_diode_green_light_top = yi_wall_diodes.wall_diode_green_light_top,
		wall_diode_green_light_right = yi_wall_diodes.wall_diode_green_light_right,
		wall_diode_green_light_bottom = yi_wall_diodes.wall_diode_green_light_bottom,
		wall_diode_green_light_left = yi_wall_diodes.wall_diode_green_light_left,
		wall_diode_red = yi_wall_diodes.wall_diode_red,
		wall_diode_red_light_top = yi_wall_diodes.wall_diode_red_light_top,
		wall_diode_red_light_right = yi_wall_diodes.wall_diode_red_light_right,
		wall_diode_red_light_bottom = yi_wall_diodes.wall_diode_red_light_bottom,
		wall_diode_red_light_left = yi_wall_diodes.wall_diode_red_light_left,
		circuit_wire_connection_point = wall_circuit_wire_connection_point,
		circuit_wire_max_distance = wall_circuit_wire_max_distance,
		default_output_signal = wall_default_output_signal,
		resistances = {
			{ type = "physical", decrease = 7, percent = 50 },
			{ type = "explosion", decrease = 5, percent = 50 },
			{ type = "fire", percent = 100 },
			{ type = "acid", percent = 30 },
		},
		pictures = {
			single = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
			straight_vertical = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
			straight_horizontal = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
			corner_right_down = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
			corner_left_down = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
			t_up = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
			ending_right = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
			ending_left = { wall_sprite("__Yuoki__/graphics/entity/walls/wall_hardic_single.png", 96, 96, { 0.5, -0.25 }) },
		},
	},
})
